services:
###
# SMD Init and Server Containers
###
  # sets up postgres for SMD data
  smd-init:
    image: ghcr.io/openchami/smd:v2.17.7
    container_name: smd-init
    hostname: smd-init
    environment:
      - SMD_DBHOST=postgres
      - SMD_DBPORT=5432
      - SMD_DBNAME=hmsds
      - SMD_DBUSER=smd-user
      - SMD_DBPASS=${SMD_POSTGRES_PASSWORD} # Set in .env file
      - SMD_DBOPTS=sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
    entrypoint:
      - /smd-init
  # SMD
  smd:
    image: ghcr.io/openchami/smd:v2.18.0-amd64
    container_name: smd
    hostname: smd
    environment:
      - SMD_DBHOST=postgres
      - SMD_DBPORT=5432
      - SMD_DBNAME=hmsds
      - SMD_DBUSER=smd-user
      - SMD_DBPASS=${SMD_POSTGRES_PASSWORD} # Set in .env file
      - SMD_DBOPTS=sslmode=disable
      # - SMD_JWKS_URL=http://opaal:3333/keys
      - SMD_JWKS_URL= # To help PCS querying hardware from SMD/HSM hardware inventory without authentication
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - SMD_WVAULT=true
      - SMD_RVAULT=true
      - DISABLE_DISCOVERY=true
    volumes:
      - ./configs/namespace:/configs/namespace
      - ./configs/token:/configs/token
    depends_on:
      postgres:
        condition: service_healthy
      smd-init:
        condition: service_completed_successfully
      opaal:
        condition: service_healthy
    ports:
      - "27779:27779"
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:27779/hsm/v2/service/ready"]
      interval: 5s
      retries: 60
      start_period: 20s
      timeout: 10s
    networks:
      - internal
